# Generated by Django 4.2.7 on 2025-12-10 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='department',
            name='fax',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='department',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='office_type',
            field=models.CharField(choices=[('directorate', 'Directorate'), ('province', 'Province'), ('province_division', 'Province Division'), ('division', 'Division'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='department',
            name='parent_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_offices', to='notices.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='department',
            name='photo',
            field=models.URLField(blank=True, verbose_name='Photo URL'),
        ),
        migrations.AddField(
            model_name='department',
            name='province',
            field=models.CharField(blank=True, choices=[('koshi', 'Koshi Province'), ('madhesh', 'Madhesh Province'), ('bagmati', 'Bagmati Province'), ('gandaki', 'Gandaki Province'), ('lumbini', 'Lumbini Province'), ('karnali', 'Karnali Province'), ('sudurpashchim', 'Sudurpashchim Province')], max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Office Name'),
        ),
    ]
